//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB1.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WEB1.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Enum_Admin {
            get {
                return ResourceManager.GetString("Enum-Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        internal static string Enum_Customer {
            get {
                return ResourceManager.GetString("Enum-Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        internal static string Enum_Female {
            get {
                return ResourceManager.GetString("Enum-Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        internal static string Enum_Male {
            get {
                return ResourceManager.GetString("Enum-Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã duyệt.
        /// </summary>
        internal static string Enum_Status_Accept {
            get {
                return ResourceManager.GetString("Enum-Status-Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa duyệt.
        /// </summary>
        internal static string Enum_Status_Unaccept {
            get {
                return ResourceManager.GetString("Enum-Status-Unaccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã tồn tại dữ liệu: .
        /// </summary>
        internal static string NotDuplicateException {
            get {
                return ResourceManager.GetString("NotDuplicateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được phép để trống trường: .
        /// </summary>
        internal static string NotEmptyException {
            get {
                return ResourceManager.GetString("NotEmptyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ Umee Shop để được hỗ trợ.
        /// </summary>
        internal static string UserMsgException {
            get {
                return ResourceManager.GetString("UserMsgException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ, vui lòng kiểm tra lại.
        /// </summary>
        internal static string ValidateException {
            get {
                return ResourceManager.GetString("ValidateException", resourceCulture);
            }
        }
    }
}
